### PR TITLE
set focus to input instantly

### PR DESCRIPTION
**Pull request by nomisum**
For me the input field didnt focus automatically. This change is a fix for that.

### CODE REVIEW

**Comment by calderaricaio** [comment]
Hi, thanks for submitting a PR. Can you tell me a few things? What version of Sketch are you using? Is it working for you? Could you please send any screenshot so I can figure out what's changed in this fix you sent? Thanks!

**Comment by nomisum** [comment]
Hi, thanks for considering. Using latest version (sketch 53).

before:
bildschirmfoto 2019-02-14 um 16 48 07

after:
bildschirmfoto 2019-02-14 um 16 47 30

**Comment by madebytincans** [comment]
Just want to confirm that this is the case for me as well.

Sketch 53
Mac v10.14.3
Magic Buttons 0.1

**Comment by calderaricaio** [comment]
Oh Cool! It's a good improvement! Will improve speed for sure! I guess that changed with new versions of Sketch. 
Thanks for adding this!

By the way, is the plugin working ok for you?
I thought it wasn't working because Sketch updated made it stop working. I'm gonna test it in the new Sketch 53 version.

**Comment by nomisum** [comment]
Other than that I'm happy. Bonus would be automatic detection of Text Override Changes instead of a shortcut, but thats not as trivial as it sounds and wouldnt really make things faster anyway, just more convenient for newbies.

**Comment by calderaricaio** [comment]
Great! Auto focus will help a lot! We appreciate a lot your contribution. I'm glad it's back working in Sketch 53! Tested right now.

I also have another idea for an improvement. When finishing edit the override will still be outdated until you release the selected item and then once you select it again it will be reloaded, maybe any idea in code that can fix it would be awesome but I'm not sure how to do it!

**Pull request merged**
